# vim: set ft=ansible tabstop=2 shiftwidth=2 expandtab
---
- name: Deprovision Instances
  hosts: all
  gather_facts: false

  tasks:
    - include_tasks: tasks/deprovision.yml
      with_items: "{{ instance_list }}"
      loop_control:
        loop_var: instance_item
