# vim: set ft=ansible
- name: Deploy on OpenStack
  hosts: all

  gather_facts: false

  tasks:
    - name: Install deps
      package:
        name: "{{ item }}"
      with_items:
        - python-devel
        - python-pip
      become: true
      become_user: root

    - name: Install shade
      pip:
        name: shade

    - name: Deploy an instance
      os_server:
        name: "{{ cloud_name_prefix }}-{{ item.name }}"
        state: present
        auth:
          auth_url: "{{ my_auth_url }}"
          username: "{{ my_username }}"
          password: "{{ my_password }}"
          project_name: "{{ my_project_name }}"
        region_name: "{{ cloud_region_name }}"
        availability_zone: "{{ cloud_availability_zone }}"
        image: "{{ cloud_image }}"
        flavor: "{{ cloud_flavor }}"
        key_name: "{{ cloud_key_name }}"
        boot_from_volume: true
        terminate_volume: true
        volume_size: 20
        security_groups: "{{ item.security_groups }}"
        auto_ip: yes
        timeout: 200
        meta:
          group: "{{ item.group }}"
          hostname: "{{ item.name }}"
      register: instances
      with_items: "{{ instance_list }}"

    - debug: var=instances.results

    - name: Add host to inventory
      add_host:
        name: "{{ item.item.name }}"
        groups: "{{ item.item.group }}"
        ansible_host: "{{ item.server.public_v4 }}"
        ansible_user: centos
        ansible_become: true
      with_items: "{{ instances.results }}"
      no_log: True
