# vim: set ft=ansible tabstop=2 shiftwdith=2 expandtab
- name: Provision Instances
  hosts: all
  gather_facts: false

  tasks:
    - include_tasks: tasks/provision.yml
      with_items: "{{ instance_list }}"
      loop_control:
        loop_var: instance_item
