# vim: ft=ansible tabstop=2 shiftwidth=2 expandtab
---
- os_volume:
    state: present
    auth:
      auth_url: "{{ my_auth_url }}"
      username: "{{ my_username }}"
      password: "{{ my_password }}"
      project_name: "{{ my_project_name }}"
    region_name: "{{ cloud_region_name }}"
    availability_zone: "{{ cloud_availability_zone }}"
    display_name: "{{ cloud_name_prefix }}-{{ instance_item.name }}-{{ item }}"
    size: 20
  when: instance_item.extra_vols is defined | default(omit)
  with_items:
    - "{{ instance_item.extra_vols | default(None) }}"

- os_server:
    name: "{{ cloud_name_prefix }}-{{ instance_item.name }}"
    state: present
    auth:
      auth_url: "{{ my_auth_url }}"
      username: "{{ my_username }}"
      password: "{{ my_password }}"
      project_name: "{{ my_project_name }}"
    region_name: "{{ cloud_region_name }}"
    availability_zone: "{{ cloud_availability_zone }}"
    image: "{{ cloud_image }}"
    flavor: "{{ cloud_flavor }}"
    key_name: "{{ cloud_key_name }}"
    boot_from_volume: true
    terminate_volume: true
    volume_size: 20
    security_groups: "{{ instance_item.security_groups }}"
    auto_ip: yes
    timeout: 200
    meta:
      group: "{{ instance_item.group }}"
      hostname: "{{ instance_item.name }}"

- os_server_volume:
    state: present
    server: "{{ cloud_name_prefix }}-{{ instance_item.name }}"
    volume: "{{ cloud_name_prefix }}-{{ instance_item.name }}-{{ item }}"
    auth:
      auth_url: "{{ my_auth_url }}"
      username: "{{ my_username }}"
      password: "{{ my_password }}"
      project_name: "{{ my_project_name }}"
    region_name: "{{ cloud_region_name }}"
    availability_zone: "{{ cloud_availability_zone }}"
  when: instance_item.extra_vols is defined | default(omit)
  with_items:
    - "{{ instance_item.extra_vols | default(None) }}"
